config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  resources :products

  resources :purchases

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one :purchase
  validates :name, presence: true
  validates :price, presence: true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    render :index
  end

  def new
    @product = Product.new 
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      # flash[:notice = "Product successfully added!"]
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end
  
  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
    
  private
  def product_params
    params.require(:product).permit(:name, :price, :purchase_id, :is_purchased)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def index
    @purchases = Purchase.all
    render :index
  end

  def new
    @purchase = Purchase.new
    render :new
  end

  def create
    @purchase = Purchase.new(purchase_params)
    if @purchase.save
      redirect_to purchases_path
    else
      render :new
    end
  end

  def show
    @purchase = Purchase.find(params[:id])
    @products = Product.all
    render :show
  end

  def edit
    @products = Product.all
    @purchase = Purchase.find(params[:id])
    render :edit
  end

  def update
    @purchase = Purchase.find(params[:id])
    if purchase_params["chk"]
        param = {"total" => purchase_params["chk"].map(&:to_i).inject(0){|sum,x| sum + x }}
        puts param
        if @purchase.update(param)
          redirect_to purchase_path
        end
    elsif @purchase.update(purchase_params)
        puts purchase_params
        # selected = params[:chk].inject(0){|sum,x| sum + x }
        puts 'selected'
        redirect_to purchases_path
    else 
        render :edit
    end
  end
  

  def destroy
    @purchase = Purchase.find(params[:id])
    @purchase.destroy
    redirect_to purchases_path
  end

  def add_prices
    total = 0
    selected = params[:chk].inject(0){|sum,x| sum + x }
    @purchase = Purchase.find(params[:id])
    # products = Product.all
    # products.each do |product|
    #   if product.purchase_id == @purchase.id
    #     total += product.price
    #   end
    # end
    puts selected
    @purchase.total = selected
    self.update
  end

  private
  def purchase_params
    params.require(:purchase).permit(:name, :total, chk: [])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= "You didnt enter something right ✋" %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price%>
  <%= f.number_field :price %>
  <%= f.submit %>
<% end %>

app/views/layouts/_purchase_form.html.erb
<%= render "layouts/errors", :object => @purchase %>

<%= form_for @purchase do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Crete+Round&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<h1>products </h1>
<iframe src="https://giphy.com/embed/beqkiz02kszV6" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/seriously-are-you-serious-antiquesroadshow-beqkiz02kszV6">via GIPHY</a></p><% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
    <hr>
      <li><%= link_to product.name, product_path(product) %></li>
      <%= "The product id is #{product.id}, 🆗 ?"%>
      <br>
      <%= "The price is  only #{product.price}! 💵"%>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet.</p>
  <iframe src="https://giphy.com/embed/beqkiz02kszV6" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/seriously-are-you-serious-antiquesroadshow-beqkiz02kszV6">via GIPHY</a></p>
<% end %>


<p><%= link_to "Create new product", new_product_path %></p>
<p><%= link_to "See all purchases or create a new purchase", purchases_path %></p>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<h1>Product: <%= @product.name %></h1>
<h2>Price: <%= @product.price %></h2>
<p><%= link_to "Edit product", edit_product_path(@product) %></p>
<p><%= link_to "Delete product", product_path(@product),
               :data => { :confirm => "Are you sure?",
                          :method => "delete" } %></p>

<p><%= link_to "Return to products index", products_path %></p>

app/views/purchases/edit.html.erb
<h1>Edit purchase</h1>

<%= render "layouts/purchase_form" %>

<% if @products.any? %>
<h4>Available products</h4>
  <%= form_for @purchase do |f| %>
    <ul>
      <% @products.each do |product| %>
        <%= check_box_tag "purchase[chk][]", product.price %>
        <%= label_tag(:product, product.name) %><br>
      <% end %>
    </ul>
      <%= f.submit %>
  <% end %>
<% else %>
  <p>There are no products yet.</p>
<% end %>

app/views/purchases/index.html.erb
<h1>purchases</h1>

<% if @purchases.any? %>
  <ul>
    <% @purchases.each do |purchase| %>
      <li><%= link_to purchase.name, purchase_path(purchase) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no purchases yet.</p>
<% end %>


<p><%= link_to "Create new purchase", new_purchase_path %></p>
<p><%= link_to "Return to main", products_path %></p>

app/views/purchases/new.html.erb
<h1>New purchase</h1>

<%= render "layouts/purchase_form" %>

app/views/purchases/show.html.erb
<h1>Purchase: <%= @purchase.name %></h1>
<h2>Total: <%= @purchase.total %></h2>


<p><%= link_to "Edit purchase", edit_purchase_path(@purchase) %></p>
<p><%= link_to "Delete purchase", purchase_path(@purchase),
               :data => { :confirm => "Are you sure?",
                          :method => "delete" } %></p>

<p><%= link_to "Return to purchases index", purchases_path %></p>